### ISSUE TITLE
Alarm border should be more flexible than strict rectangle

### ISSUE THREAD

**Issue by kasemir** [kasemir/org.csstudio.display.builder#104]
Should be rounded for rounded rectangle, circle for round LED

**Comment by kasemir** [comment]
RegionBaseRepresentation is currently using a JFX Border. The border can have CornerRadii, which would allow rounded rectangle or also the extreme case of a circle/ellipse.

For now, just one set of static, immutable borders, one per alarm severity, is used for all widgets.
Would have to create new borders for each required CornerRadii. Maybe still share the borders for the most common case of CornerRadii.EMPTY?

**Comment by kasemir** [comment]
![led](https://cloud.githubusercontent.com/assets/1932421/19390292/677a2c14-91f5-11e6-8773-36cbe39898a2.png)

**Comment by kasemir** [comment]
@claudio-rosati : Thank you, Claudio, for this idea!
Going back to EDM, BOY, .. many LEDs were configured to be alarm insensitive just to avoid the ugly border!
Now the border nicely hugs the outline of the LED, even for oval LEDs, it simply looks "right"

**Comment by claudio-rosati** [comment]
:)
