### ISSUE TITLE
Grid snapping is not working

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#106]
Grid snapping is not working: values of x and y are always 1 pixels more than the expected.
Debugging the TrackerGridConstraint class, the values are computed correctly, so the error is somewhere else.
Only when snapping to the origin (0, 0) the value have their expected values (0, 0).

**Comment by kasemir** [comment]
You're right. The 'tracker' seems to get the correct location, and the width/height is also set correctly, but the x/y are +1. I'll look at it.

**Comment by kasemir** [comment]
Bug is related to the tracker using the display model's (x, y) as an offset when determining the widget location. For many existing display files that is set to (-1, -1). Restricting the (x, y) range to start at (0, 0), and also restricting the width, height to be at least 1.

**Comment by kasemir** [comment]
Fixed the tracker, it's no longer erroneously using the Display Model's (x, y). In addition, the x, y, wind, height now have minimum values.

**Comment by claudio-rosati** [comment]
ok, can I (or you) close the issue?

**Comment by kasemir** [comment]
Yes, I think the issue has been resolved. Thanks!
