### ISSUE TITLE
Improve initial size of widgets

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#131]
Some widgets when dropped into the editor have a good initial size, letting them to be fully viewed, but some haven't.
I suggest to change the initial size of the following:
- Arc: 100, 100
- Ellipse: 100, 50
- Picture: 150, 100
- Byte Monitor: 160, 20
- Thermometer: 40, 160
- Radio Button: 100, 43 [**set the Items number to 2**]
- Scaled Slider: 200, 40

**Comment by kasemir** [comment]
Sounds good.
Go ahead, it's an easy fix, just call the 'super' constructor with the desired size as for example done in https://github.com/kasemir/org.csstudio.display.builder/blob/master/org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/TableWidget.java#L249

**Comment by claudio-rosati** [comment]
OK, I'll do it tomorrow.
