### ISSUE TITLE
Drag and Drop needs to be refined.

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#135]
Once a selected widget is dragged:
- D&D cannot be aborted (undone) via ESC key;
- Editor doesn't scroll as soon as the dragged object is close to editor's borders (I mean outside its scroll pane container);
- D&D should be aborted (undone) if object is released outside the editor's borders (I mean outside its scroll pane container).

Partially related with #132.

**Comment by claudio-rosati** [comment]
I've tried to have select & drag in a single gesture, but I've found impossible to realize it.
I start the drag on the tracked after the selection, but then the drag event are not passed correctly to the tracker, because they are owned by the original source of the event.

**Comment by kasemir** [comment]
> Can you comment about the 3rd point? Do you think it's worth some efforts?
These are all valid points. On the 3rd one, maybe objects dropped outside the visible range should be ignored?
It would be bad to unknowingly add widgets, i.e. you don't know that a widget has been dropped because you can't see it.

**Comment by claudio-rosati** [comment]
Pull request #139 fixes point 2.
Point 3 is solve by the auto-scroll on right and bottom sides. On left and top ones, the automatic clamp to 0 provided by widget's propX and propY already solved it. The only added thing was to force the tracker to the new position.

**Comment by claudio-rosati** [comment]
By the way, auto-scroll demonstrates how immature JavaFX for building professional applications: Swing supports it "natively".
