### ISSUE TITLE
Picture object displayed with a border

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#167]
As you can see, I've added a picture object loading the meter-bar.png image that is completely transparent and without border, but when displayed into the Display Editor it has a gray border that cannot be removed.

Possibly there is an incorrect css definition.

<img width="206" alt="untitled" src="https://cloud.githubusercontent.com/assets/10833922/20670586/c5d4c2ea-b579-11e6-9595-0dfd95e62f6d.png">

![meter-bar](https://cloud.githubusercontent.com/assets/10833922/20670602/e449fe84-b579-11e6-9c80-5ba14cb29698.png)

**Comment by kasemir** [comment]
Border has been removed.
