### ISSUE TITLE
Rules not working

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#172]
I'm trying to replicate a BOY behavior: a rectangle whose background is changed depending on the status of a PV.

Here the BOY rules attached to the rectangle:

![boy](https://cloud.githubusercontent.com/assets/10833922/20746039/58d43114-b6e4-11e6-80a9-0141da7ca68c.png)

and here the Display Builder rules attached to an ellipse:

![db](https://cloud.githubusercontent.com/assets/10833922/20746155/e8eee9f6-b6e4-11e6-9ab8-40f191f255bb.png)

The issue is that in Display Builder the ellipse doesn't get colored. Am I doing something wrong?

**Comment by kasemir** [comment]
Your PV is already the severity .SEVR field of the record, so just use "pv0" and not "pvSev0".

**Comment by kasemir** [comment]
Using xxx.SEVR as the PV and then "pv0" to get that value should work in both tools.

"pvSev0" only works in BOY. It's fetching the severity of a PV, and in this case severity(XX.SEVR) == severity(XX).

**Comment by claudio-rosati** [comment]
Thank you for the help, not it works fine.
Claudio
