### ISSUE TITLE
Displaybuilder build batch for Windows

### ISSUE THREAD

**Issue by pavel-ch** [kasemir/org.csstudio.display.builder#190]
Simple build batch for Windows, successfully used. Sending through issue, I do not want to make pull-request. Take it or not and close the issue.

[make.cmd.txt](https://github.com/kasemir/org.csstudio.display.builder/files/693735/make.cmd.txt)

Remove the .txt (added due to github attachment rules).

**Comment by kasemir** [comment]
Thanks, I've added it to the build directory!
