### ISSUE TITLE
'enabled' widget property

### ISSUE THREAD

**Issue by kasemir** [kasemir/org.csstudio.display.builder#210]
Related to the Q. about BOY's handling of 'enabled', https://github.com/ControlSystemStudio/cs-studio/issues/2061, and the handling of disconnected PVs, #171 :

Widgets that write PVs have an 'enabled' property which _disables_ widget interaction.
Text entry widgets that cannot write appear disabled to indicate to the user that you can't write,
Buttons that write to a PV appear disabled to indicate to the user that pushing the button won't accomplish anything.

This enable/disable mechanism is currently a runtime property, internal to the display builder runtime and its handling of PVs. It is not meant for access by scripts/PVs. In fact such scripts would be in a race condition with the widget runtime to enable or disable the widget.

Still, there can be a desire to disable control widgets based on a state of the system, because for example a certain setting is currently not applicable.
This 'enabled' property will show in the editor, it can be written by scripts or rules.
While exact details are up to the runtime of each widget, in general control widgets will appear enabled when 'enabled=true' and PVs are writable. They will appear disabled if either 'enabled=false' or the primary PV that's to be written is read-only.

'disabled' widgets still connect to PVs. A 'disabled' checkbox widget will represent the current state of the PV, you just can't click it to write to the PV.

If a script wants to disconnect a widget from its PV, it needs to set the pv_name property to empty.

**Comment by claudio-rosati** [comment]
@kasemir I'm thinking at the new meters/gauges I'm implementing, because they will have the possibility to interact with them (i.e. write value). Can I in the representation read the enable property (to enable/disable the interaction and, possibly, change how the widget is displayed) or this is just handled by the runtime?

**Comment by kasemir** [comment]
Yes, you can read the 'enabled' property and enable/disable in your own widget however you want, but I suggest you also consider write access.
Having a widget that looks enabled, user enters a new value, and that then fails, might look odd.

If you get the latest from 'master', check the TextEnty Widget and Representation.
The widget is based on the new `WritablePVWidget` that adds a `pv_writable` property.

If a widget has a `pv_name` and `pv_value` (PVWidget), the default runtime will connect the PV and update the `pv_value`. If in addition there's a `pv_writable` property (WritablePVWidget), that will reflect if there's write access.

The TextEnty representation then allows interaction if `enabled` __and__ `pv_writable`.

This means you can change the `enabled` property from a script to disable the widget.
When you enable, and there's also write access, user can enter new text.
When you enable, and but there's no write access, user cannot enter new text, only read the current value of the text.

**Comment by kasemir** [comment]
Shorter version: The `enabled` property is back to a plain property, no longer a runtime property. There's a new `pv_writable` runtime property.
Representations that are interactive, write to PVs, should combine those to allow interaction.

**Comment by claudio-rosati** [comment]
Understood.
Thank you,
Claudio
_____________________________

Claudio Rosati
Software Engineer

European Spallation Source ERIC
P.O Box 176, SE-221 00 Lund, Sweden
Visiting address: Tunavägen 24, Lund

Phone: +46 46 888 34 24
Mobile: +46 721 79 24 24
E-mail: claudio.rosati@esss.se<mailto:petra.ribb@esss.se>

www.esss.se<http://www.esss.se/>

[cid:F13AFA79-E9F7-44E8-95C8-95C364416F06]

_____________________________

EMAIL CONFIDENTIALITY NOTICE

This message is private and confidential.
If you have received this message in error,
please notify me and remove it from your system.
_____________________________

On 10 Feb 2017, at 17:36, kasemir <notifications@github.com<mailto:notifications@github.com>> wrote:


Shorter version: The enabled property is back to a plain property, no longer a runtime property. There's a new pv_writable runtime property.
Representations that are interactive, write to PVs, should combine those to allow interaction.
