### ISSUE TITLE
The dialog opened when a new display is created shows the file name field in the wrong position.

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#214]
When creating a new display file the name of the file to be created should be displayed first.

BOY display it as the first (and only one editable) field.

<img width="525" alt="boy" src="https://cloud.githubusercontent.com/assets/10833922/23062085/b8511b3a-f504-11e6-8ce8-69534d606fdf.png">

In Display Builder as second field, when the Container is probably changed less often.
So I suggest to:

- Exchange the vertical position of the 2 fields;
- Re-introduce the Full Path read-only field showing the full path of the file to be created.

<img width="525" alt="db" src="https://cloud.githubusercontent.com/assets/10833922/23062144/eef78908-f504-11e6-9dfc-190a1b9bf618.png">

**Comment by kasemir** [comment]
The logical order is 1) path 2) file, and the BOY dialog just like all the other Eclipse dialogs follow that.

I'd be OK with putting more emphasis on the file name, though:

If the "new" dialog is opened via right-click on a folder in the navigator, and the path is thus already known, that should be populated and the input focus placed on the file name right away.
..which itself is also already preset to "new_display.bob", to you can get started by only pushing "OK", nothing to type at all.

**Comment by claudio-rosati** [comment]
I understand.

Probably the easier and best thing to do is just select the name of the bob file (i.e. "new_display"), so that if you started from the right folder you have (if you want) to just type the file name and press FINISH. 

Currently the container path is selected, thus forcing to click on the file name field (or press TAB) and select only the name to be replaced by the wanted name.

**Comment by kasemir** [comment]
When opening the "New Display" wizard from the context menu of the navigator, it's almost impossible to not have a container selected. Just updated the dialog to then jump to the file name right away.

When using File/New/.., it's possible that there's no container, so in that case the container text field has the focus,
