### ISSUE TITLE
Runtime: Panning issues when zoomed

### ISSUE THREAD

**Issue by kasemir** [kasemir/org.csstudio.display.builder#229]
When changing the zoom from 100% in the display runtime, the panning (scroll bars) is still using the original size of the display.

**Comment by kasemir** [comment]
Problem is related to errouneous swap of Group vs. Pane in the scene graph below the ScrollPane.

**Comment by dheeraj539** [comment]
My requirement needs to zoom into the X-axis and keep the Y-axis as it is.
Is there a way to zoom only a particular axis at a time instead of zooming both the X and Y axis?
@kasemir

**Comment by kasemir** [comment]
When you enable zoom, you can then use the mouse
a) Inside the plot region to zoom both x & y
b) inside the time/x axis to zoom only the x axis
c) inside one of the y axes to zoom just that y axis
