### ISSUE TITLE
Symbol widget and DB changes required

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#237]
I would like to share into this issue report what I'm about to do for the symbol widget, and discuss the changes/improvements I need in the Display Builder code base in order to support it.

# General Considerations

My idea is to have a widghet where:

- multiple sets of icons/images are displayed one close to the other (possibly overlapping);
- only one icon from each set can be displayed (selected) at a given time;
- the first icon on each set is displayed by default, the other being displayed through integer PV values, rules or scripts;
- each icons set can be made visible/hidden indipendently of the currently selected icon;
- should be used to map BOY's Boolean Symbol Control and Multistate Symbol Control;
- should be possible to save the icons set content and position (and rules/scripts/PV names?) into a `.sym` file (SVG format?), in order to create reusable libraries of symbols;
- should be possible to configure a symbol widget from a previously saved `.sym` file;
- a `.sym`file dragged into the Display Builder editor should instantiate a properly configured symbol widget.

![symbol](https://cloud.githubusercontent.com/assets/10833922/26553277/35e5037e-448b-11e7-95b4-5d73dc9f105b.png)

# Customizer

To facilitate the configuration of such widgets it should be possible to open a specific customizer editor where icons/images can be graphically dragged into the widget and positioned. Moreover tools could be provided to:

- create and add an empty image filling an icon set size;
- create and add a image from a graphical font character (like Wingdings).

## API Change

To support customizers I think the following should be added:

- a boolean property named _customizable_ in the _Widget_ class (`false` by default);
- a _customize_ method in the _WidgetRepresentation_ class, having the Widget and the ToolkitRepresentation as parameters.

If the widget is _cusomizable_, then the last property in the Widget category will be a button (could be a caption/button pair named "Customizer"/"Open" or a single wide "Customize" button) invoking the widget representation _customize_ method when pressed.

The _customize_ method could be return `true` if the given widget was modified (usually when the customizer "Apply"/"OK"/"Done" button is pressed, or `false` if not (Usually when the customizer "Cancel" button is pressed).

**Comment by claudio-rosati** [comment]
@kasemir can you tell me

- what do you think;
- if you agree on the proposed API changes;
- if you can implement them or you prefer I'll do them.

**Comment by pavel-ch** [comment]
Hello, sorry for commenting from outside the project team, but I personally would think about reuse of the linking container for this purpose -> use (a simplified?) bob format internally in symbols instead of an external svg. More general layout can be possible, no need for the customizer (extra editor window?) etc. Needs to modify the heavy linking container into something more lightweight. Please ignore the comment if you consider it irrelevant.

**Comment by kasemir** [comment]
On one hand, you're free to add any type of widget. Fundamentally, a 'symbol' widget sounds like a good idea. I would suggest to keep widgets simple, though.
Good examples:
Label widget with "text".
TextUpdate widget with "pv_name".
MultiStateLED with "pv_name" and "colors[]" for the different states.
Symbol (BOY's Boolean and Multistate Symbol Control) with "pv_name" and "symbols[]" for the different states, where each symbol is an image file.

In your example, what's the minimum that users need to configure?

As for API changes, would the customize() in the representation only be called from the editor, not the runtime? Would the model even need a customizable property if that's only used for the editor?

**Comment by claudio-rosati** [comment]
@pavel-ch 
The possibility of using embedded displays (the Display Builder corresponding of BOY's linking container) already exists for who want them. Here I'm speaking of a widget to be used in place of the BOY's Boolean Symbol Control and Multistate Symbol Control.

This widget can be configured using the properties page as any other one, the customizer being only an extra tool/view to speed up the configuration process.

Being the purpose different, also the format of the file used to store this widget configuration has to be different from the `.bob` one. SVG was a proposal of a colleague: I don't have enough knowledge about it yet to say if it is convenient or not. I have to investigate. A simple one (like the `.bob` one) will be the alternative.

When this symbol widget will be available, it will be a user's choice to take advantage of the new symbol flexibility or switch back to a traditional compound approach (based on embedded displays) when "badge-like" decorations are needed.

**Comment by claudio-rosati** [comment]
@kasemir 
You're right: I want to keep things simple. The symbol widget should be like the XYPlot one: "pv_name" and "symbols[][]".

# Properties

I try to list all the relevant properties here (useful for discussion, implementation and final documentation). Suggestions and amendments are welcome.

## Widget Properties

The following are the properties applying to the widget as a whole.

| Property | Type/Values | Description |
| :--- | :--- | :--- |
| PV&nbsp;Name | String | The name of the PV used to select the current image on sets without a specific PV. |
| Width | int | The width of the widget. If not explicitly set, the width of the first image added to the widget will be used. If multiple images are added, the largest width will be used instead. |
| Height | int | The height of the widget. If not explicitly set, the height of the first image added to the widget will be used. If multiple images are added, the largest height will be used instead. |
| Scale | None, Clip, Adapt, Preserve&nbsp;Aspect | Tells how the content is displayed when the widget is resized. **None** will draw the content without any rescaling: if the widget size is smaller than its content, then drawing will occurs outside the widget bounds. **Clip** does not rescale but drawing is clipped to show only the portion of the content strictly inside the widget bounds. **Adapt** will stretch the content to fill the widget size. **Preserve&nbsp;Aspect** will scale the content preserving its aspect ratio.

**Comment by kasemir** [comment]
I find the X, Y, scale, alignment detail for each individual symbol too complicated. Also unclear how that combines with the overall `scale` property, and why an `int symbols`, wouldn't that just be the same as `len(symbols[])` ?

How about just `pv_name` and `symbols[]`, where each symbol is the name of an image file (png, svg, ..). PV is an enum or numeric type, and the widget displays `symbol[int(pv_value)]`? The image is resized to match the widget size. People can use image editing programs to prepare suitable images, the widget isn't yet another image editor on its own.

I understand that you're also interested in the 'decorator' use of images, where some icon will conditionally appear for example in the upper right corner of a widget.
I'm with @pavel-ch that this could be a separate functionality based on composing more fundamental widgets. For example, create a "Decorator" widget which is a bit like a 'group': There is one child widget, a `pv_name` and an `image`. If the PV evaluates to non-zero, the image is added as a decorator on top of the child widget. Maybe add a `location` or `alignment` property, by default `Top Right`, which allows specifying the location of the overlay. Alternatively to a group-like behavior where the `decorator` has one child widget, it could be just like the group, i.e. allow multiple child widgets, or be like the embedded widget, i.e. host a sub-display. I think the most likely use case is decorating one other widget, so hosting one child widget is likely best, where the child is resized to match the decorator widget. The example that you drew then turns into a `boolean button` widget inside a `decorator` widget.

**Comment by claudio-rosati** [comment]
OK, I like the idea of a Decorator Container widget, that I'll document in #238, because will allow for a more generic way of badging any kind of widget, not only symbols.

I summarise the new simplified Symbol widget in the following paragraphs.

# Properties
| Property | Type/Values | Description |
| :--- | :--- | :--- |
| `pv_name` | String | The name of the PV used to select the current image. It can be an enum, numeric or boolean PV (booleans being mapped to 0/false and 1/true). The widget will display `symbol[int(pv_value)]`.|
| `scale` | **Adapt**, **Preserve** | Tells how the content is displayed when the widget is resized. **Adapt** will stretch the content to fill the widget size. **Preserve** (default) will scale the content preserving its aspect ratio. |
| `symbols` | List of image files. | An ordered list of supported image files (`.png`, `.jpeg`, `.jpg`, `.gif`, …). The first image in the list is displayed by default. This property is like the `items` ina a Combo Box widget, where each entry is a file reference. |

I'm not so sure if the **scale** property can be useful or not. Probably we can remove it and just having the **Preserve** aspect ratio behavior.

# Context Menu

Right-clicking on a symbol widget should open the context menu where a **_Save As .sym…_** menu item will allow to save the widget into a `.sym` file (probably a `.bob` with just the symbol inside).

# Drag & Drop

| What | From | Into | Description |
| :--- | :--- | :--- | :--- |
| One or more supported image files. | **_Navigator_** window or OS finder. | Empty editor area. | A new Symbol widget is created containing the dropped images as `symbols`. The size will be the larger fitting all the images (i.e. [max(width[0..n-1]), max(height[0..n-1])]). |
| One or more supported image files. | **_Navigator_** window or OS finder. | An existing Symbol widget. | The dropped images will be added to the target widget `symbols` property. The size will not be affected. |
| One or more `.sym` files. | **_Navigator_** window or OS finder. | Empty editor area. | A Symbol widgets will be added for each `.sym` file. |

**Comment by kasemir** [comment]
Dragging am image file into the editor already creates a picture widget, i.e. a widget that simply shows the image. Dragging two or more images in could create a symbol widget. Dragging an image file onto a symbol widget should naturally add that image to the symbol widget's `symbols[]`.

What is the purpose of the `*.sym` file?

**Comment by claudio-rosati** [comment]
You are right about D&D. I've missing some details. Now the previous D&D table is correct: when 2 (not one) or more images are dragged and dropped int the display builder area, a dialog opens allowing to select multiple Picture widgets or a single Symbol one.

The purpose of `.sym` file is to create a library of symbols, to easily D&D one into the editor configuring only the PV Name.

**Comment by kasemir** [comment]
Your idea of a symbol library is good, but I would turn that into another separate issue, so we have:

1) Symbol widget: This issue. Widget with PV and list of images. Displays `symbols[i]` where `i` is the interger value of the PV.

2) Decorator widget: Overlays an image on the top-right corner of a widget. Maybe multiple images, maybe turns decoration on/off based on a PV. Details in #238.

3) Template library. A file that contains several widgets, maybe groups of widgets. One can drag or copy/paste those widgets into a new display. Is that just an editor window that has been made read-only, so one can copy or drag from there, but the drag is always a drag-copy, not a drag-move that would delete the content of the template? What if one updates the template, should the displays that use the template then also update? So maybe this is just a read-only display with named groups. Dragging a group from there into a new display creates an embedded widget, `file = that template`,  `group_name = that group name`, so the display embeds that group from the template?

**Comment by claudio-rosati** [comment]
I think the template library (intended as a single file) is a nice to have, but it is something different and more complex than my idea of having a "library folder" containing simple `'sym` files ready to be used. I think both could be there because one doesn't exclude the other.

**Comment by kasemir** [comment]
What then is a `sym` file? A *.bob file, but when dragging that into the editor, instead of creating an embedded display widget for that *.bob file, it pastes the content of the *.sym file? .. as a group, so it can always be moved as one item?

**Comment by claudio-rosati** [comment]
Yes, this is the idea: not inventing a new format. A `.bob` file with just a different extension (and a new attribute inside? I'm not sure of that).

**Comment by kasemir** [comment]
How can the user see what's in the *.sym file? Would need to add support for the navigator to get a preview via the file's icon.

In comparison, when you copy/paste groups from another *.bob editor that's used as a template, you see what's available beforehand.
You can already do that, except right now every editor can, well, edit.
All that's really needed: Check in the editor if the input file is read-only. If so, don't allow modifications -> Read-only *.bob files can be used as template.

**Comment by claudio-rosati** [comment]
As I have said I think both way can exists. 
At ESS we have a taxonomy for these symbols, so initially an icon/preview is not strictly necessary. Dragging from the navigator in this case has the advantage of not having another window opened. 

Both for your read-only editor and for mine of saving a `.sym` will be useful to develop a drag-outside-editor modality (SHIFT or ALT pressed?) allowing to graphically copying from a read-only editor and to save symbol dragging it from the editor into the navigator.

**Comment by claudio-rosati** [comment]
Implemented (see #261).
