### ISSUE TITLE
Scaled Slider displaying badly

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#242]
Labels are badly displayed in the following example:

<img width="418" alt="scaledslider" src="https://user-images.githubusercontent.com/10833922/27129451-9e50e954-5102-11e7-9d3a-6cb7ec4f009c.png">

<img width="285" alt="scaledsliderproperties" src="https://user-images.githubusercontent.com/10833922/27129486-d11b523e-5102-11e7-9065-e96f1ef71e5b.png">

**Comment by kasemir** [comment]
The axis labels are handled by the `javafx.scene.control.Slider`, and we then add markers for the 'High', 'Low', .. limits. Are in this case the 'High', .. markers somehow overlaying the axis labels? If the axis labels are simply wrong, that would be a bug in `javafx.scene.control.Slider`, which we can't easily modify.

**Comment by claudio-rosati** [comment]
This the current properties:
<img width="292" alt="scaledsliderfullproperties" src="https://user-images.githubusercontent.com/10833922/27134679-8adcd978-5116-11e7-8cde-b5035b3ddad6.png">

**Comment by claudio-rosati** [comment]
Puttingo to `false` all the **_Show XXX_** doesn't change the behaviour (moreover limits are depicted on the other side of the slider track).

**Comment by claudio-rosati** [comment]
This is what happens changing **_Major Ticks_** to 50:
<img width="426" alt="scaledwidgetmajorticks50" src="https://user-images.githubusercontent.com/10833922/27134832-22e8bf70-5117-11e7-8b3d-e1dc5368b834.png">

**Comment by claudio-rosati** [comment]
Today I'm in a training course, but tomorrow I'll check the JavaFX repository for this king of bug and possibly I'll open an issue.

**Comment by kasemir** [comment]
Try if changing either or both of these make a difference:
 * Enter "#.##" in the "Scale Format" property which you have empty
 * Check the "Major Ticks Pixel Dist." which is currently 40.

**Comment by claudio-rosati** [comment]
Yes, setting  "#.##" in the "Scale Format" property solve the problem. I've seen you'll already set in the code of the last commit.

**Comment by kasemir** [comment]
I think what happened is that the default `Double.toString` formatted labels like `0.3` as `0.2999999999999` and that was than too large to be displayed. Forcing a format avoids that.

**Comment by claudio-rosati** [comment]
Yes, I agree with you.
