### ISSUE TITLE
WARNING: You are binding against the deprecated org.eclipse.fx.javafx

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#253]
Hello Kay,

Have you noticed this warning just after JFXRepresentation initialisation?

**Comment by kasemir** [comment]
Yes. At the same time, when I remove that fx.javafx plugin, the class loader can't find javafx because that's an 'ext' library. Plus I still have to set those properties `-vmargs -Dorg.osgi.framework.bundle.parent=ext -Dosgi.framework.extensions=org.eclipse.fx.osgi`

**Comment by kasemir** [comment]
So for the time being I accepted the warning and ignore the warning.

**Comment by claudio-rosati** [comment]
OK, thank you.
