### ISSUE TITLE
Unable to build Display Builder.

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#257]
I'm unable to build Display Builder after switching to the new DIIRT (see [#2238](https://github.com/ControlSystemStudio/cs-studio/issues/2238#issuecomment-316083702)).

Currently this is blocking my development. Have you an idea how can I solve the problem?

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.0.0:compile (default-compile) on project org.csstudio.display.builder.representation.javafx: Compilation failure: Compilation failure:
[ERROR] /Users/claudiorosati/Projects/GitHub/org.csstudio.display.builder/org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/plots/ImageRepresentation.java:[297]
[ERROR] image_plot.setValue(image.getWidth(), image.getHeight(), new ArrayByte(image.getData(), true),
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The constructor ArrayByte(ListNumber, boolean) is undefined
[ERROR] 1 problem (1 error)
```

**Comment by kasemir** [comment]
There is a VImage branch that I need to merge (likely: Re-visit, because the diirt VImage changes started way back).
But my build is broken waiting on https://github.com/ControlSystemStudio/cs-studio/pull/2201 to get resolved, so that the vtype pv can provide the new VImage.

**Comment by kasemir** [comment]
Fixed compiler error in 947b942

**Comment by kasemir** [comment]
The compiler error has been fixed. I need to check what's holding up the merge of 2201, but have some other local work to complete before that.

**Comment by claudio-rosati** [comment]
Thank you Kay
