### ISSUE TITLE
Dialogs

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#285]
On my Mac (not on Linux) opening a rule dialg to set a color is painful, because when the color dialog pops up, the rule one pops up again, and the the color, and so on.

I open this issue to remember to use the new popup window used to edit the knob value and see what happens.

**Comment by kasemir** [comment]
I noticed that as well.

The original problem is that 'modal' JFX dialogs aren't enforced by the SWT FXCanvas.
The rule, script, widget info, ... dialogs can thus move below the RCP window, and then users wonder why the application stops reacting to mouse input.
As a fix, the JFX dialogs are now forced to the front every second, but that's imperfect when there's yet another sub-dialog.

The ultimate fix will be Phoebus: No SWT window, no FXCanvas, and modal dialogs that work as they're meant to work.

**Comment by claudio-rosati** [comment]
I agree with you, but if we can find a solution that works also on SWT, why not? Maybe not for all dialogs (I mean the rules one is probably too big for a popover, but colors, fonts are good candidates).

**Comment by claudio-rosati** [comment]
SEE #317

**Comment by kasemir** [comment]
Fonts and colors have been converted into popovers.
.. plus the slider and scollbar also have a popover for the increment.
Rule and script dialogs are indeed too large, plus they often benefit from being able to reposition and resize.
Suggest to close this issue.

**Comment by claudio-rosati** [comment]
I'll probably reqork the font popover to reduce it size a bit and improve the workflow.
I also think Rules and Scripts dialogs could be made more compact without losing usability... I'll think about them. I would like to have them as popover to avoid the dialog problems in the current version od the cs-studio integration: what the original popover implementation allows detaching the popover (if enabled): that could be interesting for those big ones.
