### ISSUE TITLE
Representation.dispose() not called when a (runtime) window is closed

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#287]
@kasemir it seems that when you close the CS-Studio tab containing a runtime Display Builder OPI, the Representation.dispose() method is not called.

This is crucial for my controlled knob because I have to release the midi device used for that widget, otherwise it will not work anymore if you re-open the OPI.

Is it something that can be fixed? Am I overriding the wrong method?

**Comment by kasemir** [comment]
The RuntimeViewPart, i.e. the SWT view registers a disposeListener,
https://github.com/kasemir/org.csstudio.display.builder/blob/master/org.csstudio.display.builder.rcp/src/org/csstudio/display/builder/rcp/RuntimeViewPart.java#L348

The onDispose then calls representation.shutdown, https://github.com/kasemir/org.csstudio.display.builder/blob/master/org.csstudio.display.builder.rcp/src/org/csstudio/display/builder/rcp/RuntimeViewPart.java#L631

Maybe onDispose also needs to call toolkit.disposeRepresentation() for the current model?
I'll have to check details when I'm back in the office.

**Comment by claudio-rosati** [comment]
> currentValueBarArc

It really depend on the meaning and purpose of the `dispose` and `shutdown` methods. 

I'll try to see if moving my disposal code to the shutdown solve the problem. I'll let you know.

**Comment by kasemir** [comment]
Do you see dispose being called when you load a different model into the same view (i.e. button with action that loads different model)?

**Comment by claudio-rosati** [comment]
Yes, I've tried with `01_main.bob` and when the new model is loaded the call happens.

**Comment by kasemir** [comment]
Good. So toolkit.disposeRepresentation() is called when changing the model, but not on shutdown.

-> toolkit.disposeRepresentation() needs to also call toolkit.disposeRepresentation().

**Comment by claudio-rosati** [comment]
I've tried to add it on RuntimeViewPart.disposeModel but it seems not being the right place.

**Comment by kasemir** [comment]
When you close the runtime view, onDispose is called, which calls then calls representation.shutdown.

The model already calls toolkit.disposeRepresentation() when it changes the model within the same view, but it doesn't call it when closing the view

==> Call toolkit.disposeRepresentation()  - if there is a current model represented in the View - in onDispose.

**Comment by claudio-rosati** [comment]
There is something strange that I don't understand.

Here what in `RuntimeViewPart`:

```
    /** Invoke close_handler for model */
    private void disposeModel()
    {
        final DisplayModel model = active_model;
        active_model = null;
        if (model != null  &&  close_handler != null)
            close_handler.accept(model);
    }

    /** View is closed. Dispose model and toolkit representation */
    private void onDispose()
    {
        disposeModel();
        representation.shutdown();
        // No longer track when view is hidden/restored
        getSite().getPage().removePartListener(show_hide_listener);
    }
```

`close_handler` is `ActionUtil::handleClose` that performs the following:

```
    /** Passed to newly opened windows to handle runtime shutdown
     *  when window is closed
     *  @param model Model for which runtime needs to be closed
     */
    public static void handleClose(final DisplayModel model)
    {
        // Called on UI thread
        // Stop runtime in background thread
        RuntimeUtil.getExecutor().submit(() ->  RuntimeUtil.stopRuntime(model) );

        // .. while UI thread removes the representation
        final ToolkitRepresentation<Object, Object> toolkit = ToolkitRepresentation.getToolkit(model);
        toolkit.disposeRepresentation(model);
    }
```

So, in theory, `toolkit.disposeRepresentation(model)` is already called.

**Comment by kasemir** [comment]
Maybe the `active_model` is already null for some reason?

Or RCP isn't actually calling onDispose. In some cases it just hides the view without disposing it.

**Comment by kasemir** [comment]
As far as I can tell, each widget representation is disposed.

To test, I added a printout to JFXBaseRepresentation:
```
    public void dispose()
    {
        System.out.println("Disposing representation for " + model_widget);
...
```

When I close a RuntimeView, I see a printout for each widget.

**Comment by claudio-rosati** [comment]
I'll test on my again today or tomorrw (I'm moving to the site ;-)

**Comment by claudio-rosati** [comment]
@kasemir 
I can see the following kind of message when I close the stand-alone editor:

```
...
2017-10-18 14:48:15 FINE [org.csstudio.display.builder.representation.ToolkitRepresentation] Disposing org.csstudio.display.builder.representation.javafx.widgets.ActionButtonRepresentation@788c30b4 for Widget 'Action Button_12' (action_button)
...
```

but nothing is written when I close the editor/or the runtime window in CS-Studio.

**Comment by kasemir** [comment]
Have you enabled logging at the FINE level in RCP?

**Comment by claudio-rosati** [comment]
@kasemir here is the situation:

- first I've not understood how logging works: using the Logging Configuration nothing changed. I had to enable FINE in Preferences > CSS Core > Logging. But a this point I was bombarded by jca messages (even if Logging Configuration says com.cosylab... loggers are all to INFO);
- second, looking at the message I've found that embedded displays are disposed, but **NOT** their content: this is currently my problem.

I tried a simple OPI with a single Controlled Knob and it is correctly disposed. If now I create a new OPI embedding the simple one, the Embedded Display is disposed, but not its content (i.e. the Controlled Knob).

The change I made in the `EmbeddedDisplayRepresentation` seems solve the problem. I'll do a pull request: please check if the solution is correct.

**Comment by kasemir** [comment]
Ah, it's about the content of _embedded_ displays. Good find!
