### ISSUE TITLE
Strange "Properties" panel behavior on delete

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#290]
Pick a widget and drag it on the editor: the widget is drawn and selected, the Properties panel is updated accordingly.

Now just delete the widget (pressing the DEL keyboard key): the widget is deleted but the Properties panel still contains the properties of the deleted widget, properties that can be edited.

I think that when a widget is deleted, the display properties should be displayed.

**Comment by kasemir** [comment]
Similar: Undo/Redo of cut/copy/paste can leave a selection rectangle in place for widgets that no longer exists.
