### ISSUE TITLE
Meter Widget Limits

### ISSUE THREAD

**Issue by kasemir** [kasemir/org.csstudio.display.builder#296]
Meter configured with min .. max range of 0 o 360, _not_ reading range from PV:

![m2](https://user-images.githubusercontent.com/1932421/31737186-b179b9dc-b414-11e7-89f7-0a7816510124.png)

.. shows a range of 0 to 400:

![m1](https://user-images.githubusercontent.com/1932421/31737098-79f5332e-b414-11e7-86e0-c3e90c2d346d.png)

In some cases, 'rounding' might be useful, but in this case it's about a rotation angle of 0..360 degree that user expects to see.

**Comment by kasemir** [comment]
Related: The BOY 'Gauge' widget looked very much like a "meter" with skin set to "GAUGE", so would be nice to get that when importing *.opi files.

**Comment by kasemir** [comment]
@claudio-rosati  I assume the behavior of the meter is defined in the underlying ESS knobs library.

**Comment by claudio-rosati** [comment]
Range is one of the things Medusa is not so good. I have to look at it also to implement logarithmic scale. Tomorrow i’m on vacation. I’ll look at in on Friday

**Comment by claudio-rosati** [comment]
In the Medusa one.

**Comment by claudio-rosati** [comment]
I’ve almost completed the fix. On Monday i’ll pull request for merge
