### ISSUE TITLE
Symbol widget doesn't update the image for initial value of real PV

### ISSUE THREAD

**Issue by kasemir** [kasemir/org.csstudio.display.builder#299]
Screenshot shows the on/off switch type of symbol from examples/monitors_symbols.bob, assigned to PVs from a real IOC.

The index indicator shows the correct 0 vs. 1 value of the PV, but the images both reflect the 0 state:

![symbol](https://user-images.githubusercontent.com/1932421/31833587-fe4e7272-b598-11e7-9366-316e988a6050.png)

@claudio-rosati  Looks like an initialization error.
Once the PV changes, the image updates, but if the initial value of a PV is 1, the symbol widget often shows the 0 state image.

**Comment by kasemir** [comment]
Just to clarify, screenshot shows two symbol widgets, connected to different PVs. "Left" PV is 0, "right" PV has a value of 1.

**Comment by claudio-rosati** [comment]
You're right: it seems an initialization problem. Initially the widget supported loading of images in a different thread, but not the its onw initialization. Then I've moved the initialization itself onto a different thread too. Probably this is the cause. I'll figure out and fix the problem.
