### ISSUE TITLE
Zoom-related problems

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#304]
1. Usually when a copied object is pasted it happens at the current cursor location. When zoom is engaged the paste location seems to not keep in account the current zoom level, resulting in a paste outside the current view.

1. Dragging an object outside the current view (letting the view automatically scroll) is painful when a large zoom factor is engaged (e.g. 200%). The view jump to some improbable locations making impossible to work (see the attached video).

[zoom-drag.mov.zip](https://github.com/kasemir/org.csstudio.display.builder/files/1437178/zoom-drag.mov.zip)

**Comment by kasemir** [comment]
I'll fix the zoomed 'paste'. It's similar to zoom-aware 'drop' which I recently fixed in 7a7916b

I agree that the AutoScrollHandler has issues.
To me, even without zooming it tends to move the edit area either too slowly or too rapidly.

**Comment by claudio-rosati** [comment]
Keep the issue open, I'll try to give a look at the auto-scroll next week.

**Comment by kasemir** [comment]
OK. The 'paste' is now good.

**Comment by claudio-rosati** [comment]
Thank you Kay.

**Comment by claudio-rosati** [comment]
@kasemir 
I have the same problem with Polylines and Polygons when zomm is not 100%

**Comment by kasemir** [comment]
Yes, in 'append' mode. I'll fix that. 'Edit' mode for moving existing points is fine.

**Comment by kasemir** [comment]
Thanks for finding all these little issues. Fixed the poly edit when zoomed.

**Comment by claudio-rosati** [comment]
In the styleguide I'm writing I've decided to redo following the ESS rules some visually bad OPIs I've found googling the web. So I'm using Display Builder as a "user" rather than a "programmer"... Probaly I'll discover more things, but it's better I'll do it rather than my stakeholder.

**Comment by kasemir** [comment]
Closing this, since the 'paste' and 'poly*' editing with zoom is for now good.
