### ISSUE TITLE
Tooltip not modifiable at runtime if empty

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#334]
Look at the following example:

[empty tooltip problem.bob.zip](https://github.com/kasemir/org.csstudio.display.builder/files/1681842/empty.tooltip.problem.bob.zip)

Changing the value of the spinner should change the labels' tooltip, but this happens only if the label was provided with a non-empty tooltip, otherwise no tooltip is displayed.

**Comment by kasemir** [comment]
This is on purpose, see javadoc in https://github.com/kasemir/org.csstudio.display.builder/blob/master/org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/TooltipSupport.java#L53:

```   
// Suppress tool tip if _initial_ text is empty.
// In case a script changes the tool tip at runtime,
// tool tip must have some initial non-empty value.
// This was done for optimization:
// Avoid listener and code to remove/add tooltip at runtime.
if (tooltip_property.getValue().isEmpty())
          ...
```

--> Set the tooltip to some initial value if you do want a tooltip.

**Comment by kasemir** [comment]
> Set the tooltip to some initial value if you do want a tooltip.

You can even set it to " " spaces to assert that there will be a tooltip that you later update to its actual value.

**Comment by claudio-rosati** [comment]
OK, thank you. I'll inform the users about that.
