### ISSUE TITLE
Display background not changed when embedded.

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#337]
#### Overview description

I have a display whose background is changed by a rule. When this disply is embedded into another one, then its background doesn't change with the rule.

#### Steps to reproduce

1. Run `CSSTUDIO-559.bob` and change the spinner value (with its buttons): the background changes according a display's rule.
2. Now run `CSSTUDIO-559-embedder.bob` and to the same: the embedded widget's content doesn't change its background.

[Archive.zip](https://github.com/kasemir/org.csstudio.display.builder/files/1689881/Archive.zip)

**Comment by kasemir** [comment]
Should now work

**Comment by claudio-rosati** [comment]
Thank you Kay.
