### ISSUE TITLE
Colorpicker 'custom color' selection hangs on linux

### ISSUE THREAD

**Issue by kasemir** [kasemir/org.csstudio.display.builder#339]
In the JavaFX ColorPicker, selecting one of the presented colors works fine, but clicking on "Custom color..." to select another color hangs on Linux.

Similar to what's described on https://bugs.openjdk.java.net/browse/JDK-8124032, which is reported as resolved, but still happens with both Java 8 & display builder on RCP and Java 9 & phoebus, when running on RHEL 7.4.

**Comment by kasemir** [comment]
Since widget color dialog already offers ways to select arbitrary color via R, G, B, A, simply hiding the troublesome "Custom color..." link seems like a practical workaround.

**Comment by claudio-rosati** [comment]
Have you done it or do you want me do it in the dialogs revision process I'm involved now?

**Comment by claudio-rosati** [comment]
Ohoops... I've seen now you have already done it.
I've improved it a little: #340.
I think we can close this issue.
