### ISSUE TITLE
CSSTUDIO-569: The Action Button text gets left aligned when the word-wrapping is engaged.

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#343]
Normally a short text is centred in an Action Button.
Long text in an Action Button high enough is word-wrapped, but it will no more centred, but left-aligned.

[CSSTUDIO-569.zip](https://github.com/kasemir/org.csstudio.display.builder/files/1710105/CSSTUDIO-569.zip)

**Comment by kasemir** [comment]
Fixed

![wrap](https://user-images.githubusercontent.com/1932421/36312431-7cc71e22-12fc-11e8-90c4-f00199adc5af.png)

**Comment by claudio-rosati** [comment]
Thank you Kay.
