### ISSUE TITLE
CSSTUDIO-568: Incorrect macro expansion if macro has defaul value

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#344]
When using a macro with a default value [e.g. macro FINAL set to $(MAY_NOT_BE_SET=default_value)]: the macro expansion works if the macro only appears once in an expression. So, $(FINAL) works as expected, but $(FINAL)/$(FINAL) does not.

Test case attached, main display is macro_tester.bob, it embeds macro_test with and without setting the MAIN macro.

[CSSTUDIO-568.zip](https://github.com/kasemir/org.csstudio.display.builder/files/1710125/CSSTUDIO-568.zip)

**Comment by kasemir** [comment]
Curious, because this test passes:
```   
Macros   macros = new Macros();
macros.add("DERIVED", "$(MAIN=default)");

assertThat(MacroHandler.replace(macros, "${DERIVED}"), equalTo("default"));
assertThat(MacroHandler.replace(macros, "/${DERIVED}/${DERIVED}/"), equalTo("/default/default/"));

macros.add("MAIN", "main");
assertThat(MacroHandler.replace(macros, "${DERIVED}"), equalTo("main"));
assertThat(MacroHandler.replace(macros, "/${DERIVED}/${DERIVED}/"), equalTo("/main/main/"));
```

Is that the same idea?

**Comment by kasemir** [comment]
Found the problem. It only happened with "$()", not with "${}".

With `$(M=default) $(M=default)` it used to find one macro `M` with default value `default) $(M=default`.
Now it finds two macros `M`, each with default value `default`.
