### ISSUE TITLE
Group height not saved (possibly not updated)

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#348]
I put few widgets whose total height is higher than 200, select them and create a group. 

The I copy the group from the Outline view, and paste it... the group width is the expected value , while the heigh is now 200. I set it to the current value and save.

Looking ad the `.bob` file, height is not saved.

**Comment by claudio-rosati** [comment]
I've tried to write manually the height value in the `.bob` file and it is read and used correctly. So the problem seems related to **group widget not writing (serialising) the height**.

**Comment by kasemir** [comment]
> The I copy the group from the Outline view, and paste it... the group width is the expected value , 
> while the heigh is now 200.
Cannot reproduce.
1) Open 01_main.bob in editor
2) Select the left-most set of widgets starting with the "Information" label and down
3) Create Group (-> height 328)
4) Copy in outline view, using context menu in outline view
5) Paste somewhere in display by locating mouse there and pressing Ctrl-V
--> Copied group with height 328

**Comment by claudio-rosati** [comment]
@kasemir please try with the attached file.

[issue #348.bob.zip](https://github.com/kasemir/org.csstudio.display.builder/files/1724425/issue.348.bob.zip)

The group is 300x300 (I had to write the height manually on the file). Try to select it, copy and paste. The new group should now have the height set to 200. Save it and reload: the original group has now the height set to 200. If you look at the saved file, the first group has no height at all, the second one, instead, has it set to 300.

**Comment by kasemir** [comment]
Check the GroupWidget source code:
Line 192 in the constructor sets the default size of the group to 400 x 300:
{{{
   public GroupWidget()
    {
        super(WIDGET_DESCRIPTOR.getType(), 400, 300);
    }
}}}
At the end of `defineProperties` there's a commit from you, dated 2016-09-13, that changes the size:
{{{
    @Override
    protected void `(final List<WidgetProperty<?>> properties)
    {
        super.defineProperties(properties);
        properties.add(macros = propMacros.createProperty(this, new Macros()));
        properties.add(children = new ChildrenProperty(this));
        properties.add(style = propStyle.createProperty(this, Style.GROUP));
        properties.add(font = propFont.createProperty(this, WidgetFontService.get(NamedWidgetFonts.DEFAULT)));
        properties.add(foreground = propForegroundColor.createProperty(this, WidgetColorService.getColor(NamedWidgetColors.TEXT)));
        properties.add(background = propBackgroundColor.createProperty(this, WidgetColorService.getColor(NamedWidgetColors.BACKGROUND)));
        properties.add(transparent = propTransparent.createProperty(this, false));
        properties.add(insets = runtimePropInsets.createProperty(this, new int[] { 0, 0 }));

        // Initial size
        propWidth().setValue(300);
        propHeight().setValue(200);
    }

What's happening: The height property has a default of 300, i.e. a value of 300 is not saved to the file.
But then the define_properties changes the default to 200.

--> 300 is not saved, and then you get 200.

I'll change the default, defined in the constructor, to 300x200 because that seems to be a default that you prefer, and remove the changes in `defineProperties`.
}}}

**Comment by claudio-rosati** [comment]
Thank you Kay. I really don't remember why I did it... possibly a left over? Or more probably I wanted to reduce a bit the initial size, doing it in the wrong place (2016-09-13 seems few months after starting working at ESS on CS-Studio).
