### ISSUE TITLE
Better way of creating groups

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#349]
The group creation from the context menu **Create Group** add extra space because of the group border. If a different border is needed (or no border at all) this extra size is not updated, and manual adjustment must be performed.

I suggest to create a submenu attached to **Create Group** with the list of the available different groups (borders) in order to create the right one from the beginning.

**Comment by kasemir** [comment]
Selecting a set of widgets..

![g1](https://user-images.githubusercontent.com/1932421/36209610-263d5bfe-116a-11e8-8d44-7e207ac3d0aa.png)

 and then invoking 'Create Group' creates a group such that the widgets stay at their original location:

![g2](https://user-images.githubusercontent.com/1932421/36209618-2a0b121c-116a-11e8-8712-d298dbcbc2f4.png)

When you then invoke "Remove Group", you're basically back where you started.

==> This is good behaviour and needs to be preserved.


When you change the group style, the changing border affects the overall size of the widget and thus the widgets inside the group appear to move: 

![g3](https://user-images.githubusercontent.com/1932421/36209622-2d4c4e6e-116a-11e8-9ffb-425b3962e0f4.png)


If you want to update the editor such that changing the group style will also adjust the group's position in a way that the child widget locations are preserved on the screen, I'm fine with that.

**Comment by claudio-rosati** [comment]
@kasemir 
I perfectly understand the current approach: the group surround the selected objects leaving them in the same looking position. The problem is the border itself: designing OPIs for the accelerator often you want to group them without the border. So grouping then changing the style to NONE creates the problem.

What I'm not sure is if it is better (and easier) to updated the group position when style is changed or, instead, allowing to chose the style when the group is created, through a popup menu.

**Comment by kasemir** [comment]
It's easier to only allow selecting the style once when the group is created,
but it's better to allow changing the style and then always adjusting the position when the style changes.

**Comment by claudio-rosati** [comment]
OK, I'll work on it.
