### ISSUE TITLE
Fonts definition not working

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#350]
@kasemir this is something discovered today and it is a **blocking** bug.

- Create a new _font file_ assigning a different font to the _Default_ one (something visually different from the Liberation Sans one), and select it in the Display Builder **Font File** preferences.
- Restart CS-Studio.
- Create a new _Label_ widget and look at its **Font** property: it should say `Default` but it is not the one previously defined.
- Open the Font popover and you should see `Liberation Sans Regular 14` defined as _Default_. Select a different font by name (e.g. _Comment_) and then _Default_ again: now the new definition of _Default_ appears. Press **OK**: nothing changes in the label widget.
- Resize a bit the widget: the correct font is now used.
- Save, close and reopen the OPI: Liberation Sans is still used instead of the correct one.

Could it be related to the application of the `DEFAULT` class to the widget? Is it possible that the class uses the "default" font definition instead of the new one?

**Comment by kasemir** [comment]
The font file is read, and when I set
```
Default      = Liberation Sans - bold - 30
```
that information is getting into the WidgetFontPopOver line 90 where it fetches the named fonts.
But then something fails.
"30" is not one of the items in the list of font sizes. You can manually enter 30, but it's not one of the suggested sizes. Maybe the problem is related to that.
Have to investigate.

**Comment by claudio-rosati** [comment]
OK. Tell me if is something you will do, or I will instead.

**Comment by kasemir** [comment]
I'm working on it.

**Comment by kasemir** [comment]
Problem was use of font constants like DEFAULT instead of performing a lookup of the current definition, based on reading the font.def.

Named colors are already performing a lookup whenever used, so they don't exhibit the same issue.

**Comment by claudio-rosati** [comment]
It works nice for me now.
I close the issue.
