### ISSUE TITLE
Another problem with tooltip and macros

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#369]
It not clear to me if this issue can be related with #364 

Anyway, the default content on the Tooltip changes when a widget is replaced with another one (contextual menu -> Replace With). The replacement seems evaluating the macros, adding something weird.

[CSSTUDIO-619.zip](https://github.com/kasemir/org.csstudio.display.builder/files/1824955/CSSTUDIO-619.zip)

**Comment by kasemir** [comment]
Fixed.

**Comment by claudio-rosati** [comment]
Thank you Kay
