### ISSUE TITLE
Display line numbers in script editor

### ISSUE THREAD

**Issue by mark0n** [kasemir/org.csstudio.display.builder#383]
Errors in scripts are reported by line number. It would be great if the editor for embedded scripts would display line numbers.

**Comment by kasemir** [comment]
I think the `SyntaxHighlightedMultiLineInputDialog` had line numbers, but there's currently a technical problem with including it in the product, #379, so we're for the time being back to a plain text editor.

**Comment by claudio-rosati** [comment]
@kasemir 
This is now solved. Should we close the issue?
