### ISSUE TITLE
Allow access to macros from rules/scripts

### ISSUE THREAD

**Issue by mark0n** [kasemir/org.csstudio.display.builder#384]
Access to macros from rules and scripts would be useful.

A typical use case would be screens for many similar devices (just different macros). Let's say there is one widget that makes sense for all but one of these devices. In this case it would be great if we could hide it for this particular case using a rule like this: visible if macro deviceType!="special device".

Maybe the macros could be pulled in similar to the PVs? In the rule itself we could then refer to them by saying `macro[0]`.

**Comment by kasemir** [comment]
You do have access to macros from within a script:
```
value = widget.getEffectiveMacros().getValue("NAME_OF_MACRO")
# Note that value might be None if that macro is not defined
```

**Comment by kasemir** [comment]
Also:
```
for name in widget.getEffectiveMacros().getNames():
    print ("I have a value for %s" % name)

```

**Comment by mark0n** [comment]
Cool, thanks. You might want to add that to the documentation.

**Comment by kasemir** [comment]
In principle, the online help includes the Javadoc for a subset of the widget API.
It shows that the Widget has a `getEffectiveMacros()` that returns `Macros`:

<img width="982" alt="screen shot 2018-05-11 at 7 00 03 pm" src="https://user-images.githubusercontent.com/1932421/39950196-a16576b4-554d-11e8-9a24-ef3ac7f5708a.png">

That in turn has `getValue(..)` and so on:

<img width="810" alt="screen shot 2018-05-11 at 7 00 28 pm" src="https://user-images.githubusercontent.com/1932421/39950202-a76c2f9e-554d-11e8-8ccb-1bea8321823d.png">

Depending on how the site-specific product is assembled, there may be a problem with not always including that section of the help.
