### ISSUE TITLE
Undo on groups doesn't work properly

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#403]
- Create a group with some widgets inside.

<img width="329" alt="i1" src="https://user-images.githubusercontent.com/10833922/41241972-a1792056-6d9e-11e8-868f-cb11ba6d563e.png">
<img width="147" alt="i2" src="https://user-images.githubusercontent.com/10833922/41241979-a676bfb4-6d9e-11e8-8988-8bf5f3741c52.png">

- Select the content widgets from bottom-up on the Overview then drag them out of the group.

<img width="580" alt="i3" src="https://user-images.githubusercontent.com/10833922/41242045-db7e47cc-6d9e-11e8-9d91-fe491368bf0f.png">
<img width="122" alt="i4" src="https://user-images.githubusercontent.com/10833922/41242053-df1cfe50-6d9e-11e8-853a-4b18d578bd40.png">

- Now press the UNDO button: now the content is in the reverse order and the group itself is smaller than before.

<img width="344" alt="i5" src="https://user-images.githubusercontent.com/10833922/41242137-073a67a6-6d9f-11e8-9f8e-072003bfc78b.png">
<img width="156" alt="i6" src="https://user-images.githubusercontent.com/10833922/41242140-0945a678-6d9f-11e8-91a4-923be42b5a9b.png">

**Comment by kasemir** [comment]
Fixed in phoebus version
