### ISSUE TITLE
Archiver link to a PV can't be established if the PV name has macro inside.

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#405]
I report the problem my colleague Miklós Boros found.

The problem is that the `.plt` editor (DataBrowser) checks the PV name and the Archiver server availability even in design mode.

Step1: search a PV in the Archiver Browser after you have a valid archiver IP set in the preferences.
Step2: drag&drop it into the `.plt` editor (DataBrowser).

It works.

Now change the PV name so it contains a macro.For example: 

`(CrS-PHS:Cryo-PI-3130:Pressure) -> (CrS-PHS:Cryo-PI-${Tank}30:Pessure)`

The link to the archiver server is immediately deleted, because it can't resolve the macro in design time. 

Solution to this is to allow the user to connect the PV to the archiver manually too. This is why we have right click in the bottom of my attached screen. Display Builder should not check the current availability of the PV nor the Archiver server only in runtime mode.

![screenshot-1](https://user-images.githubusercontent.com/10833922/41277245-f414cbf2-6e26-11e8-9c3a-6ece638d3d0a.png)
![screenshot-2](https://user-images.githubusercontent.com/10833922/41277248-f5bb26d6-6e26-11e8-8f5f-2e99a7d86458.png)

**Comment by kasemir** [comment]
The display builder knows if its in edit mode or not, so yes, it should pass that info down into the Data Browser controller which then skips the archive optimization. I'll do that next week when back from the meeting.

**Comment by claudio-rosati** [comment]
Thank you.

**Comment by kasemir** [comment]
Has been fixed, the archive data source is no longer removed for channels that contain macros which are to be resolved later.
