### ISSUE TITLE
CheckBox and DataBrowser names

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#409]
CheckBox and DataBrowser widgets are the only one using a compound, camel-case name, instead of a space-separated one.

Moreover, DataBrowser has the corresponding full-view tool named Data Browser in the CS-Studio ➜ Trends menu.

I suggest to rename them to Check Box and Data Browser

**Comment by kasemir** [comment]
Done

**Comment by kasemir** [comment]
Phoebus already named them like this.
