### ISSUE TITLE
Regional settings are ignored when changing a PV value

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#412]
Displaying numbers in Text Updates and Text Entries follows the rules of the regional settings (decimal symbol being comma instead of dot) when **displaying** the value. When trying to **change** the value in a Text Entry a dot has to be used, independently of the current locale.

**Comment by claudio-rosati** [comment]
Or we get rid of the locale also in displaying a value, or we have to allow it in text entries.

**Comment by claudio-rosati** [comment]
P.S.
I can fix it, once we decided how.

**Comment by kasemir** [comment]
Try now.

**Comment by claudio-rosati** [comment]
Thank you Kay.
I'm waiting feedback from the integrator raising the problem. I'll close the issue if everything is ok.

**Comment by claudio-rosati** [comment]
Integrators are happy.
Thank you.
