### ISSUE TITLE
Colour problems with DataBrowser 3

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#417]
During commissioning at ESS people is start using DataBrowser 3 with a dark background because of the better contrast.

Here the problems:

- Black cannot be used as background because otherwise the X axis and scale cannot be seen;
- If a white (or very light colour) is used for the track, its value cannot be seen in the crosshair cursor because of its white background;
- The crosshair itself is strangely displayed.

My suggestions to solve the problem are the following:

- In the **Misc.** properties add the **Foreground** property set by default to white;
- Use the **Foreground** property
  - to paint the X axis and scale,
  - to paint the inner line of the crosshair,
  - to paint the outline of the crosshair values (on the axis and on the graph),
  - to paint the crosshair values (on the axis and on the graph);
- Use the Background property
  - to paint the graph background (as it works now),
  - to paint the outer lines of the crosshair,
  - to paint the background of the crosshair values  (on the axis and on the graph).

![db3](https://user-images.githubusercontent.com/10833922/42942154-5e599e3e-8b5f-11e8-9b14-dc012aab7006.png)

**Comment by kasemir** [comment]
I can add a 'foreground' color.

**Comment by claudio-rosati** [comment]
Thank you.

**Comment by kasemir** [comment]
Also sets the 'grid' to shade of the foreground color, and uses the background for the markers:

![xx](https://user-images.githubusercontent.com/1932421/42950420-f7db3130-8b41-11e8-916b-77d1e7caf7db.png)

**Comment by claudio-rosati** [comment]
Thank you Kay.
