### ISSUE TITLE
Standalone windows behave differently from other CS-Studio windows

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#422]
Here the original problem from my integrators:

> The problem is that standalone window will not have the zoom bar any more. But zoom is used quite a lot to make the graphics fill the whole window. Is it possible to enable zoom on those windows too?

Inside CS-Studio (maybe on Phoebus it's different) we have the following 3 window's possibilities ("Replace" a part) with their pros, cons, and problems:

- **New Workbench Window**
  - It opens a new window whose existence, location and size are remembered;
  - The ZOOM selector is available and its value is remembered;
  - The window needs extra space for the toolbar, tabs bar and status bar;
  - Other tabs can be added to the window.
  - Right-click opens the contextual menu.
- **New Tab**
  - It opens a new tab that can be detached and moved in a different screen (and/or workbench);
  - Existence, oosition, size are remembered (on MacOS X position on a different screen is not restored);
  - The ZOOM selector is available and its value is remembered;
  - The window needs extra space for the tabs bar;
  - Other tabs can be added to the window.
  - Right-click opens the contextual menu.
- **Standalone Window**
  - Opens a new window only containing the OPI, without any extra space used;
  - Position is remembered (also on different screens), but not size and existence;
  - No ZOOM control, but zoom can be set via CTRL/CMD + WHEEL. Zoom is not remembered.
  - Right-click doesn't open the contextual menu.

I suggest the following enhancements for the **Standalone Window** mode:

- Open a contextual menu with right-click (this probably is of very low priority if the Phoebus integration will allow to get rid of the CS-Studio version of DB soon, otherwise not);
- Add a "Zoom…" entry in the contextual menu to open a dialog containing the ZOOM control (this could be always an option, standalone or not);
- Save and restore the window's size and zoom value;
- Save and restore its existence.

**Comment by kasemir** [comment]
'Standalone' now is a detached RCP part with context, zoom, perspective, 

#434
