### ISSUE TITLE
Rules regression

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#423]
@kasemir 
This is a bad regression on Rules that is blocking our commissioning.

If you put a that simple expression in a rule

>(pv0>=0) && (pv0<=10)

the corresponding script is wrong and not running

>if (pv0>==0)  and  (pv0<==10):

![f](https://user-images.githubusercontent.com/10833922/43515332-81b15278-9582-11e8-8faf-84275c89b217.png)

Is that related to you recent changes on the script engine?

[CSSTUDIO-774.bob.zip](https://github.com/kasemir/org.csstudio.display.builder/files/2248981/CSSTUDIO-774.bob.zip)

**Comment by kasemir** [comment]
There was an update to patch '=' into '==' to handle legacy rules.
That needs to become more specific to preserve '>=' and '<='.

**Comment by kasemir** [comment]
https://github.com/kasemir/org.csstudio.display.builder/commit/cc6ad7c6816ded973d5d966f043efc8e465b14b4 fixed the '=', with test. Needs another go to preserve '>=' and '<='.

**Comment by claudio-rosati** [comment]
Can you do the fixes?

**Comment by kasemir** [comment]
Just did

**Comment by claudio-rosati** [comment]
Thank you so much.
