### ISSUE TITLE
Compatibility problem with standalone windows

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#424]
When a standalone window is opened, it will be sized to the Display width/height, and the titlebar shows the Display's name.

If a button in this display opens another Display **replacing** the current one, the window's size and the title bar are not updated.

See the attached file and compare with the BOY samples.

[CSSTUDIO-773.zip](https://github.com/kasemir/org.csstudio.display.builder/files/2252719/CSSTUDIO-773.zip)

**Comment by kasemir** [comment]
Display Builder has no "Standalone" window that tries to implement many of the RCP behaviors on top of a Shell. Instead, it uses a normal workbench window, #422 (or with Phobus removes all of RCP).
Opening a different display will not resize the workbench window.

**Comment by claudio-rosati** [comment]
OK Understood.
