### ISSUE TITLE
No context menu on OPI opened as Standalone Window

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#434]
If you open a **Standalone Window**, you'll not be able to have the usual contextual menu, allowing to send the PV of a right-clicked widget to DataBrowser and other PV consumers.

If the OPI is, instead opened as a **New Workbench Window** or **New Tab** it works fine.

I understand that this is related to open an SWG menu from a pure JavaFX window, but is currently a serious issue.

[CSSTUDIO-812.zip](https://github.com/kasemir/org.csstudio.display.builder/files/2302353/CSSTUDIO-812.zip)

**Comment by kasemir** [comment]
Don't use standalone windows. They were introduced by DLS for BOY to be pure Shell windows which are then managed via X windows commands, without support for paerspectives, save/restore, context menu, ..

I'll update the display builder to handle them just like 'new window', and in Phoebus the issue is obsolete because single-content windows visually look like 'standalone'.

**Comment by willrogers** [comment]
This should work, it certainly works for me.

I think there are circumstances where the click menu can be lost, but it certainly works in almost all cases.

**Comment by willrogers** [comment]
Sorry, my comment was referring to BOY.

**Comment by kasemir** [comment]
'Standalone' display builder windows are now detached RCP parts. So they have no toolbar, i.e. they have the desired minimalistic look, but they're still integrated with context menu, perspective save/restore is enabled, and ScriptUtil.closeDisplay() works on them.

**Comment by claudio-rosati** [comment]
Thank you Kay. I'm rebuilding and the test it. I'll close the issue.

**Comment by claudio-rosati** [comment]
It works... but... the window is not correctly sized. The new Tab bar height should be added to the overall windows height, otherwise scrollbars appear.

**Comment by kasemir** [comment]
Try to determine the height of the tab that works for you on your computer right now, and put that into a pull request.

**Comment by claudio-rosati** [comment]
OK
