### ISSUE TITLE
Missing labels in ByteMonitor

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#438]
My colleagues are complaining about the impossibility to add labels to the ByteMonitor, thing possible in BOY.

From what I've seen, in all the cases they are using a PV providing a (static) array of strings. So I'm thinking to 2 possible alternative implementations:

- Adding a new PV to the ByteMonitor providing the array of strings to be used for the label, or
- Create a ByteStringMonitor widget that displays only array of string, left-/centred-/right-aligned with the possibility to rotate the whole array in steps of 90 degrees.

I personally like the second option, that leaves the ByteMonitor untouched, and allows for placing the labels on both sides of a ByteMonitor.

@kasemir 
What do you think about?

**Comment by claudio-rosati** [comment]
Hello @kasemir 
Importing is ByteMonitor with labels doesn't work as expected. Here the BOY example:

![screenshot 2018-10-30 at 13 59 11](https://user-images.githubusercontent.com/10833922/47719623-0851bd80-dc4c-11e8-9ac1-70bed49df030.png)

and here the imported one:

![screenshot 2018-10-30 at 14 00 57](https://user-images.githubusercontent.com/10833922/47719700-3fc06a00-dc4c-11e8-8be5-e22150606349.png)

The main problems are the following:

- Imported labels are reversed: **Label #1** is top/left instead than bottom/right;
- Imported labels are aligned with the wrong led/bit.
- Foreground colour is not applied to the labels.

I'll patch it: #464

**Comment by kasemir** [comment]
Worked for me, the case that had to be handled was using the "square" option and "reversed bits":

![a](https://user-images.githubusercontent.com/1932421/47723241-7be2d300-dc2a-11e8-9e16-2b0a6482ae43.png)

![b](https://user-images.githubusercontent.com/1932421/47723249-7f765a00-dc2a-11e8-9f7a-2c3af29a6e62.png)

Can you check if that still works with your changes?

**Comment by claudio-rosati** [comment]
Now yes:

![screenshot 2018-10-30 at 15 05 25](https://user-images.githubusercontent.com/10833922/47724330-c0846380-dc56-11e8-9729-3f73c26f0e3e.png)

![screenshot 2018-10-30 at 15 14 48](https://user-images.githubusercontent.com/10833922/47724336-c417ea80-dc56-11e8-9f78-361f38189ffc.png)

**Comment by claudio-rosati** [comment]
@kasemir 
In my original JIRA issue I've found the following:

> BOY ByteMonitor allows for labels to be specified. It is a property of the widget and its type is String[], **allowing to be set via rule directly from PV**. This feature is missing in Display Builder's ByteMonitor widget.

Clearly the bold sentence cannot be done in Display Builder. I'll add the bit index to the label name.

**Comment by kasemir** [comment]
I've reconsidered: Instead of converting *.opi files into *.bob where label widgets are added to the bye monitor, I'll add a "labels" property to the byte monitor as in BOY.

**Comment by claudio-rosati** [comment]
OK, that will solve also the possibility of updating the labels as a whole from PV.
Thank you

**Comment by claudio-rosati** [comment]
I'm sorry @kasemir but I don't like the new implementation:

- First (as you can see in the attached picture) labels are horizontally centred with their LEDs but not vertically in both vertical and horizontal ByteMonitors;
- It is impossible now to obtain the original BOY configuration with labels outside the LEDs (this could be dome adding a `Labels Position` property with 3 values: BEFORE_LEDS, INSIDE_LEDS, AFTER_LEDS. So the horizontal ByteMonitors in BOY will use BEFORE_LEDS, and the vertical one AFTER_LEDS).
- Font cannot be set.

![screenshot 2018-11-01 at 10 04 56](https://user-images.githubusercontent.com/10833922/47842650-9d27f880-ddbd-11e8-8477-4acc2869eefa.png)

So the new implementation has the advantages of having back the `Labels` property, but has lost the flexibility of the separated labels (font and position).

**Comment by kasemir** [comment]
Font can be set: 3323cbadb3e7db6bf3f461453ab57d3fb25db74c

**Comment by kasemir** [comment]
As for the vertical alignment, your right, isn't it curious that the alignment is off?
I cannot see why, though. Maybe the Text bounds are not valid at the time they're used?
But then why is the horizontal alignment correct?

As for the position, I'll look at adding an option.

**Comment by kasemir** [comment]
BOY didn't have a 'position' option.
Instead, square LEDs used the widget size, centering the labels in the LED.
Round LEDs were always circular, placing the label on the side, requiring you to pick the correct widget size, otherwise the labels are truncated.

![leds](https://user-images.githubusercontent.com/1932421/47852251-97c4b100-ddb1-11e8-9fd2-e52ff9d94d4b.png)

**Comment by claudio-rosati** [comment]
Yes, it's true... but we can do better or just be compatible.

**Comment by claudio-rosati** [comment]
@kasemir 
My PR #465 should solve the vertical alignment of the labels.

**Comment by kasemir** [comment]
Now it's as in BOY, except for a minor detail how vertical labels get truncated when they're too long.

![bytes](https://user-images.githubusercontent.com/1932421/47867627-6dd2b500-ddd8-11e8-943a-03f6a0050ee8.png)

**Comment by claudio-rosati** [comment]
Perfect.
I've tested it and now the conversion it's fine.
Thank you
