### ISSUE TITLE
Still problems with rules

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#441]
Strange problems with the ! character in strings:

![f0](https://user-images.githubusercontent.com/10833922/45038286-3b6b3c80-b061-11e8-835c-639a376d13c1.png)

**Comment by kasemir** [comment]
Please paste screenshot of the complete rules dialog.
Also, try using " instead of '

**Comment by kasemir** [comment]
Works now:

![rule](https://user-images.githubusercontent.com/1932421/45045393-cab42800-b040-11e8-9481-f8ab28be5183.png)

**Comment by claudio-rosati** [comment]
Thank you for the fix.
