### ISSUE TITLE
ERROR building Display Builder

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#448]
Hello Kay,

my line manager decided to have a color box close to each Jenkins builds to have a quick look on failed and successful JUnit tests. This was done adding `junit "**/surefire-reports/*.xml"` to the build pipeline.

After that, all the newly executed pipelines are yellow-colored because there are errors in the JUnit tests, but the tests don't failed.

The error is at the line n. 3037 of the attached log file of the Display Builder build.

```
Results :

Tests in error: 
  JythonTest.testPathWithThreads:152 » Execution java.lang.AssertionError: 
Expe...

Tests run: 16, Failures: 0, Errors: 1, Skipped: 0

[ERROR] There are test failures.
```

Have you noted it before? Can be fixed?

[5_org.csstudio.display.builder.log.zip](https://github.com/kasemir/org.csstudio.display.builder/files/2415304/5_org.csstudio.display.builder.log.zip)

**Comment by kasemir** [comment]
The error with more detailed stack trace is in line 3500:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.011 sec <<< FAILURE! - in org.csstudio.display.builder.runtime.test.JythonTest
testPathWithThreads(org.csstudio.display.builder.runtime.test.JythonTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.AssertionError:
Expected: a string containing "always"
     but: was "['/Users/claudiorosati/.m2/repository/p2/osgi/bundle/org.python.jython/2.7.0.release/org.python.jython-2.7.0.release.jar/Lib', '__classpath__', '__pyclasspath__/']"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.csstudio.display.builder.runtime.test.JythonTest.createInterpreter(JythonTest.java:92)
```

Yes, I see that occasionally, as mentioned in the code comment:
```
// Meant to check for https://github.com/ControlSystemStudio/cs-studio/issues/1687,
// where presumably the following happened:
//
// 1) Jython is initialized, once
// 2) When a Jython interpreter instance is created, it's configured with additional path elements
// 3) When that Jython interpreter is later used, occasionally it seems to revert to the
//    basic path from step 1, ignoring its configuration from step 2.
//
// The problem appears related to usage of ThreadLocal in org.python.core.ThreadStateMapping.
// Setting all path elements once in step 1 seems to fix the problem,
// but it would be nice to demonstrate the original issue in a unit test.
//
// Unfortunately, very hard to duplicate. Only rarely see the test fail:
//  Expected: a string containing "special"
//  but: was "['/tmp/always', '/usr/local/hudson/config/jobs/CSS_display.builder/workspace/org.csstudio.display.builder.runtime.test/target/work/plugins/org.python.jython_2.7.0.release/Lib', '__classpath__', '__pyclasspath__/']"
//   at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
//   at org.junit.Assert.assertThat(Assert.java:956)
//   at org.junit.Assert.assertThat(Assert.java:923)
//   at org.csstudio.display.builder.runtime.test.JythonTest.testInterpreter(JythonTest.java:115) // old line number
//   at org.csstudio.display.builder.runtime.test.JythonTest.lambda$2(JythonTest.java:136)        // old line number
```

This refers to a known problem, https://github.com/ControlSystemStudio/cs-studio/issues/1687. In the spirit of test-driven-development, there's a test to duplicate the problem.
Alas, seldom see it fail. Here's my last build output, sails right through that test:
```
Running org.csstudio.display.builder.runtime.test.JythonTest
Jython home: file:/home/kasemir/.m2/repository/p2/osgi/bundle/org.python.jython/2.7.0.release/org.python.jython-2.7.0.release.jar
Jython provided as JAR
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.072 sec - in org.csstudio.display.builder.runtime.test.JythonTest
testPathWithThreads(org.csstudio.display.builder.runtime.test.JythonTest)  Time elapsed: 6.035 sec
```

If it fails for you every time, then maybe you can try to figure out why that is happening and fix it?
It's been too elusive for me to follow up.

**Comment by claudio-rosati** [comment]
Yes, 11 times on 11 runs can be said it always happens here.
I try.

**Comment by claudio-rosati** [comment]
Clearly, running the test from Eclipse works fine.

**Comment by kasemir** [comment]
> running the test from Eclipse works fine

The way it's executed clearly seems to matter here.
The code in the test is conceptually simple enough, like this:
```
python = new PythonInterpreter({ path that contains "/tmp/special" })
assertThat(python.path.contains("/tmp/special"))
```

In my tests, be it from the IDE or Hudson/maven, that almost always works out.
But in operation as well as tests we sometimes see that the python interpreter falls back to some basic state instead of the one passed to the constructor, so the path lacks the desired entries.
For scripts in BOY, display builder, scan server, ... this means that they fail to locate some imports.
I suspect this is based on the use of threadlocal, where Jython decides to use a previously initialized state instead of the one passed to the constructor. So the outcome depends on which thread invoked the code, and what has happened before. But so far I have not figured it out.

**Comment by claudio-rosati** [comment]
Running the following on my mac it always happens

```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
MVNOPT="-B -P ess-css-settings,platform-default,csstudio-composite-repo-enable,eclipse-sites"
(cd org.csstudio.display.builder; time mvn $MVNOPT --settings ../ess-css-extra/maven/settings.xml -Dcss_repo=file:/Users/claudiorosati/Projects/GitHub/ess-css-extra/ess_css_comp_repo clean verify) | tee -a 5_org.csstudio.display.builder.log
```

where `org.csstudio.display.builder` is a clone of your repository (really is a clone of the fork).

**Comment by claudio-rosati** [comment]
@kasemir 
I found this thing strange: instead of

```javq
    @Test
    public void testPathWithThreads() throws Exception
    {
        // Initialize on some other thread
        executor.submit(() -> init()).get();

        for (int i=0; i<RUNTIME_SECONDS; ++i)
        {
            final ExecutorService new_executor = Executors.newSingleThreadExecutor();
            new_executor.submit(() ->
            {
                final PythonInterpreter python = createInterpreter();
                ...
```

I've tried with

```java
    @Test
    public void testPathWithThreads() throws Exception
    {
        for (int i=0; i<RUNTIME_SECONDS; ++i)
        {
            final ExecutorService new_executor = Executors.newSingleThreadExecutor();
            new_executor.submit(() ->
            {
                init();
                final PythonInterpreter python = createInterpreter();
                ...
```

so the initialisation is on the same thread, and I have the same problem.

I have also tried to create the`/tmp/always` and the `/tmp/special` on my disk, but nothing improved.

**Comment by kasemir** [comment]
This matches my experience of not understanding what's happening.
Why is the PythonInterpreter created like this ignoring the provided state/path,
and instead uses the settings of some previously created setup?
```
python = new PythonInterpreter({ path that contains "/tmp/special" })
assertThat(python.path.contains("/tmp/special"))
```

If this could be reproduced in the IDE, I could step through in the debugger.
But a mvn-triggered test failure, invoking a jython.jar where you cannot add print statements, complicates matters.

**Comment by claudio-rosati** [comment]
Can this be the sign of opening a ticket with the Jython community?

**Comment by claudio-rosati** [comment]
I've also unsuccessfully tried to update Jython to ver. 2.7.1 (the last one available) without success.

**Comment by claudio-rosati** [comment]
A last thing: I don't understand the purpose of the test. 
It seems to me more to prove a possible bug in Jython rather than testing a feature in Display Builder and Scanner. I am correct?

**Comment by claudio-rosati** [comment]
Putting

```java
final PySystemState state = new PySystemState();
// Check for default settings
assertThat(state.path.toString(), containsString("always"));
assertThat(state.path.toString(), not(containsString("special")));
```

at the very end of the `init()` method, just after the `PythonInterpreter.initialize(...)` statement, will move the error on the first of the two `assert` statements. Being that, looking at the `PySystemState`, the state can be initialised only once, this means that it was done before the `PythonInterpreter.initialize(...)` is actually performed, but I don't understand when and by whom.

**Comment by claudio-rosati** [comment]
I found cause and solution: commenting out the single test inside `JythonScriptTest` it works.

This means that in my machine(s) JUnit executes `JythonScriptTest` **before** `JythonTest`, thus the `PySystemState` will be already initialised when `JythonTest` is executed. In your case, because of the unpredictability of the JUnit tests order, the tests are executed in a reversed order.

The solution is a test suite where the order is explicitly defined. I'll do it now.

**Comment by kasemir** [comment]
Very good! That explains why we sometimes see the failure and sometimes not.
Interesting how the 'random' JUnit execution order happened to always pick the failing case for your setup but neither Travis nor my Hudson setup. Certainly shows that it's good to execute the tests, and I'm happy that there _was_ this test.
Thanks!

**Comment by claudio-rosati** [comment]
@kasemir 
Do you want I do pull requests for update to Jyton 2.7.1, or can I delete those branches from my local repository?

**Comment by kasemir** [comment]
Sure.
Phoebus uses 2.7.1, https://github.com/shroffk/phoebus/blob/master/dependencies/phoebus-target/pom.xml#L79, so that should be OK.
