### ISSUE TITLE
Problems with Table widget.

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#449]
Hello Kay,

I don't understand why, using a Table Widget not attached to a PV, when the OPI is run a strange row is inserted containing `VString[No PV, 1970/01/01 01:00:00.000]`.

A colleague needs an empty table with 3 columns not connected to a PV that will be populated pressing some buttons. But the "empty" Table widget appears with this first annoying row.

![screenshot 2018-09-26 at 14 31 44](https://user-images.githubusercontent.com/10833922/46080024-0c944200-c199-11e8-8af5-f104f56f95a6.png)

**Comment by claudio-rosati** [comment]
Moreover, trying to set the value to `None` instead of empties the table displays `null`.

![screenshot 2018-09-26 at 14 38 06](https://user-images.githubusercontent.com/10833922/46080276-d0151600-c199-11e8-9ea8-54065e7fecec.png)

and the following message:

```
WARNING [Thread 1] org.csstudio.javafx.StringTable (setData) - Table needs 3 columns [Column 1, Column 2, Column 3] but got row with just 1: [null]
```

**Comment by kasemir** [comment]
Try now.

**Comment by claudio-rosati** [comment]
It worked fine.
Thank you for the quick fix.
