### ISSUE TITLE
Verbose XML

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#454]
Some colleagues of me want to generate `.bob` file automagically from the IOC database and metadata from the ESS IOC Factory service.

Being that there is no documentation about the `.bob` XML file format and the current files contains only data for what is different from the default values, it is impossible for them doing the same they have already dome in the past for BOY.

I'm thinking to add a new "verbose" preference to Display Builder to change the way `.bob` files are saved.

@kasemir what is your opinion about it?

**Comment by kasemir** [comment]
I'd rather keep the display files small.
Those who want to create the files by other means should also create minimal files,
containing only the properties that need to change.
You can see that property name in the tooltip of each property in the editor.
But if you prefer to create large display files, that's now a preference option you requested.

**Comment by claudio-rosati** [comment]
Generally speaking I agree with you. The problem is that without a proper `.xsd` document or other kind of documentation describing the exact format of the XML and the actual default values, it becomes difficult for the integrators producing their `.bob` without continuously jump to CS-Studio and try things and compare the resulting `.bob` file. With the verbose option at least they can create their template OPI having a file containing everything to look at.

Thank you having added it.
