### ISSUE TITLE
Problems with macros in rules

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#484]
A macro inside the rule's **Value** is expanded (at edit time too).
A macro inside the rule's **Boolean Expression** is not (neither at edit time, nor at runtime).

<img width="1159" alt="screenshot 2019-01-07 at 10 25 16" src="https://user-images.githubusercontent.com/10833922/50759979-cb670000-1266-11e9-81c0-f376ae4e31f5.png">

In the picture `$(LINEWIDTH)` is se to 30, while `$(LIMIT)` to 25.

[CSSTUDIO-647.bob.zip](https://github.com/kasemir/org.csstudio.display.builder/files/2732117/CSSTUDIO-647.bob.zip)

**Comment by kasemir** [comment]
Try now.

**Comment by claudio-rosati** [comment]
It works now.
Thank you.
