### ISSUE TITLE
Problems with the Display Builder toolbar actions.

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#507]
Hello Kay,

first the for toolbar buttons to manipulate the widget position and size don't have all the tooltip, and I think the Distribute one is assigned to the wrong button. In the following picture in blue is the current tooltip content, in red the suggested one.

<img width="391" alt="Screenshot 2019-03-15 at 14 26 14" src="https://user-images.githubusercontent.com/10833922/54434802-5b299e80-472f-11e9-86e5-5f01fc729e28.png">

The here are problems on how Align and Distribute works.

### Align 

The following self-describing OPI explain well some of the problems with Align.

[CSSTUDIO-973.zip](https://github.com/kasemir/org.csstudio.display.builder/files/2971302/CSSTUDIO-973.zip)

<img width="391" alt="Screenshot 2019-03-15 at 14 11 49" src="https://user-images.githubusercontent.com/10833922/54435167-2cf88e80-4730-11e9-96a6-abefdb187acc.png">

Is my opinion that:

- The selection, any kind of, made with any of the possible ways, defines a bounding box;
- TOP should align the top border of all widgets with the top border of the bounding box;
- BOTTOM should align the bottom border of all widgets with the bottom border of the bounding box;
- MIDDLE should align the center of all widgets with the center of the of the bounding box;
- Similarly for LEFT, RIGHT and CENTER.

This is not what happens now. I you agree on the behaviour I can fix it.

### Distribute

If you select the 3 labels with a lazo-drag from bottom-right to top-left and then select "Distribute horizontally", then they are redistributed according to the order in the Outline, instead of the visual one.

**Comment by kasemir** [comment]
The alignment was implemented to match the behavior of EDM and BOY, i.e. the previous EPICS display tools that we had used.
But what you describe is closer to what for example Power Point does, so let's do that.

Can you implement this in separate pull requests, i.e. tool tip, then alignment, then distribute?

**Comment by claudio-rosati** [comment]
Absolutely.

Can you give me a hint on which part of the code look at?

**Comment by kasemir** [comment]
Toolbar: org.csstudio.display.builder/org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/DisplayEditor.java line 194: createToolbar()

Then see ActionDescription.ALIGN_CENTER which is mentioned in there how they're doing the alignment.
