### ISSUE TITLE
Class styles will not apply to group widget if inside tab container

### ISSUE THREAD

**Issue by MaticPogacnik** [kasemir/org.csstudio.display.builder#516]
If group widget (maybe also others? didn't test) is inside tab container class properties will not apply if class definition file (*.bcf) is updated.
Workaround: extract group container as separate screen and add it as embedded display.

**Comment by kasemir** [comment]
Indeed:
 * Create display with Label of type "SECTION" at top level
 * Create display with Label of type "SECTION" inside a group
 * Create display with Label of type "SECTION" inside tabs
 * Update the class definition, for example the color of a "SECTION" label 
 * In editor, invoke "Re-load Widget Classes"

--> The label inside Tabs will not reflect the new color.
Will look into this.

**Comment by kasemir** [comment]
The issue should be limited to widgets within Tabs, and has been fixed.
