### ISSUE TITLE
Problems using DataBrowser 3 in Display Builder

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#521]
I have a problem related to a long wait time when starting CS-Studio in control room where it is supposed to open an OPI containing a DataBrowser widget.

Here are the exceptions I've received from the operator:

[CSReport.txt](https://github.com/kasemir/org.csstudio.display.builder/files/3007770/CSReport.txt)

**Comment by kasemir** [comment]
Duplicate of #462

**Comment by claudio-rosati** [comment]
Thank you Kay. For some reasons I've lost the link to #462.
I've now asked the operator to delete the `.metadata` folder. If it works I'll close #462 too.

**Comment by kasemir** [comment]
That's of course a workaround, not a solution, but at this time I don't have a better solution.
