### ISSUE TITLE
Line style option in DataBrowser

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#525]
I have a request (CSSTUDIO-1002) from out accelerator people now working on commissioning to add more line styles to DataBrowser because when you start to have more than a few tracks colour alone doesn't help enough in visually distinguish them,

The request was for having:

- SOLID
- DASHED (- - - -)
- DOTTED (・・・・)
- DASH-DOTTED (-・-・-・-)

@kasemir I can do it on both the DataBrowser and the widget. If you prefer to do it, or have other ideas please let me know.

Moreover, it could also be the time to improve font and colour selection as per #471

**Comment by kasemir** [comment]
I'll do it. But you may not be able to use it until the Java 11 build problems are solved.

**Comment by claudio-rosati** [comment]
Do you mean "Java 11 build problems for Eclipse-based CS-Studio"?
That's fine for me. I've just asked out infrastructure group to provide a Jenkins machine with Java 11 installed for the new release of CS-Studio. And I still have to understand what to change in the ESS product too.

**Comment by kasemir** [comment]
Note it's on a 'java8' branch because the CS-Studio build from 'master' is broken for me.

**Comment by kasemir** [comment]
Never mind, it's also on 'master', but it's left as an exercise to build with the current RCP CSS master.

Will next update phoebus.

**Comment by claudio-rosati** [comment]
OK, thank you.
Also I'm still using Java 8 on my forked repositories because the master is broken and I'm waiting a Java 11 Jenkins machine to start working on it.

**Comment by claudio-rosati** [comment]
It works fine.
Thank you for the prompt implementation.
