### ISSUE TITLE
Display Builder should not issue CA search requests for "not fully resolved" PV names

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#530]
Probably somehow related to #529.

At runtime a widget with a PV name containing a non defined macro is sending CA search requests that inevitably will fails and saturate the network with useless requests.

Moreover, at runtime the `Widget 'XXX' (xxx) 'pv_name' is not fully resolved: ...` messages should be logged as WARNING or ERROR instead of INFO (that it's fine in editor mode).

**Comment by kasemir** [comment]
I've increased the log level so unresolved macros are now a warning.

It is, however, outside of the realm of the display to decide if a PV is valid or not. Yes, it will create PVs that may contain unresolved macros, but the underlying issue is the same as generally mistyped PVs: We simply create them, no idea if they will ever be able to connect.

**Comment by claudio-rosati** [comment]
Thank you Kay.

>It is, however, outside of the realm of the display to decide if a PV is valid or not.

Yes, I agree, and it is what I've tried to explain to my colleague. The answer was that, being we recognise there is a problem with the macro leading to a "_pv_name_ is not fully resolved", we should not "create them".

**Comment by kasemir** [comment]
Other display tools like EDM also search for the names as received, i.e. including unresolved macros.

The bigger issue is typos in PV names. Operational sites tend to use casnooper to locate ongoing PV searches as a result of mistyped PVs. Having the unresolved macros show up together with the other typos is generally helpful.

**Comment by pavel-ch** [comment]
Tested on Phoebus, but should be the same.
This new warning seems to catch too much cases:
- warnings are issued in the Editor, too. But in Editor it is a usual situation to have some top level macros unresolved
- warnings are issued for all properties, like tooltip etc. Is this desirable?
- with tooltip like $(pv_name)\n$(pv_value), the warning printout makes multiline artifacts in the log

**Comment by claudio-rosati** [comment]
Discussion is going on at ESS about what is better to do.
I close this issue. If something new come out I'll re-open it or I'll post a PR.
