### ISSUE TITLE
Sizing an object to 0 or less in any direction wil produce a lot of exceptions.

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#97]
Sizing an object to 0 or less in any direction wil produce a lot of exceptions.
In certain cases (e.g. Scrollbar) the object disappear from the editor.

**Comment by claudio-rosati** [comment]
The scrollbar problem was another thing and already solved by @kasemir

**Comment by kasemir** [comment]
Enforcing minimum width/height avoids the problem.

I think that's a solution, because widgets with width/height of 0 are not practical anyway.
If we do come up with a widget where 0 wid/hei makes sense, more changes would be required to allow for this.
